services:
  app:
    build: .
    container_name: app
    ports:
    - 8082:80
    depends_on:
      mysql:
        condition: service_healthy
        restart: true
  mysql:
    image: mysql:9.1
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: fred
      MYSQL_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10